name: Build FFmpeg ARMv7 with MediaCodec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Android NDK
        run: |
          mkdir -p /home/runner/android-ndk
          cd /home/runner/android-ndk
          curl -sSL https://dl.google.com/android/repository/android-ndk-r26c-linux.zip -o ndk.zip
          unzip -q ndk.zip
          mv android-ndk-* ndk
          echo "$PWD/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
        shell: bash

      - name: Build FFmpeg
        run: |
          set -e
          export API=21
          export NDK=$ANDROID_NDK_HOME
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export AR=$TOOLCHAIN/bin/llvm-ar
          export AS=$TOOLCHAIN/bin/llvm-as
          export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang
          export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang++
          export LD=$TOOLCHAIN/bin/ld
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          export NM=$TOOLCHAIN/bin/llvm-nm
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export SYSROOT=$TOOLCHAIN/sysroot

          cd ffmpeg
          make distclean || true
          git clean -fdx || true

          ./configure \
            --prefix=$PWD/build/armeabi-v7a \
            --target-os=android \
            --arch=armv7a \
            --cpu=armv7-a \
            --enable-shared \
            --enable-gpl \
            --enable-jni \
            --enable-mediacodec \
            --enable-decoder=h264_mediacodec \
            --enable-decoder=hevc_mediacodec \
            --enable-decoder=mpeg4_mediacodec \
            --enable-encoder=h264_mediacodec \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --disable-vulkan \
            --disable-libdrm \
            --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
            --cc=$CC \
            --cxx=$CXX \
            --ar=$AR \
            --nm=$NM \
            --strip=$STRIP \
            --ranlib=$RANLIB \
            --sysroot=$SYSROOT \
            --extra-cflags="-O3 -fPIC" \
            --extra-ldflags="-lm"

          make -j2
          make install
        env:
          ANDROID_NDK_HOME: /home/runner/android-ndk/ndk
          ac_cv_header_vulkan_vulkan_h: no
          ac_cv_lib_vulkan_vulkan: no

      - name: Prepare output
        run: |
          mkdir -p "${{ github.workspace }}/output"
          cd ffmpeg/build/armeabi-v7a
          zip -r "${{ github.workspace }}/output/ffmpeg-armv7-mediacodec.zip" .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-build-${{ github.run_number }}
          name: Automated Build ${{ github.run_number }}
          body: Automatikusan generált FFmpeg ARMv7 + MediaCodec build.
          files: ${{ github.workspace }}/output/ffmpeg-armv7-mediacodec.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
