name: Android FFmpeg Build with MediaCodec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: 'latest'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential pkg-config git unzip

      - name: Download NDK
        run: |
          mkdir -p $HOME/android-ndk
          cd $HOME/android-ndk
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c ndk

      - name: Build FFmpeg for ARMv7 with MediaCodec
        run: |
          export API=21
          export NDK=$HOME/android-ndk/ndk
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export AR=$TOOLCHAIN/bin/llvm-ar
          export AS=$TOOLCHAIN/bin/llvm-as
          export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang
          export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang++
          export LD=$TOOLCHAIN/bin/ld
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          export NM=$TOOLCHAIN/bin/llvm-nm
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib

          git clone https://github.com/FFmpeg/FFmpeg ffmpeg
          cd ffmpeg
          ./configure \
            --prefix=$PWD/build/armeabi-v7a \
            --target-os=android \
            --arch=armv7a \
            --cpu=armv7-a \
            --enable-shared \
            --enable-gpl \
            --enable-jni \
            --enable-mediacodec \
            --enable-decoder=h264_mediacodec \
            --enable-decoder=hevc_mediacodec \
            --enable-decoder=mpeg4_mediacodec \
            --enable-v4l2-m2m \
            --disable-vulkan \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
            --cc=$CC \
            --cxx=$CXX \
            --ar=$AR \
            --nm=$NM \
            --strip=$STRIP \
            --ranlib=$RANLIB \
            --sysroot=$TOOLCHAIN/sysroot \
            --extra-cflags="-O3 -fPIC" \
            --extra-ldflags="-lm"
          make -j$(nproc)
          make install

      - name: Package APK
        run: |
          mkdir -p output
          echo "Ez lenne a helye az APK csomagolásnak, itt beilleszthető az Android Studio build lépés."
          zip -r output/ffmpeg-armv7-mediacodec.zip ffmpeg/build/armeabi-v7a

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/ffmpeg-armv7-mediacodec.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
