name: Build FFmpeg GUI Android (ARMv7)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config autoconf automake build-essential libtool git unzip

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Download and unpack NDK
      run: |
        sdkmanager --install "ndk;25.2.9519653"

    - name: Clone FFmpeg
      run: |
        git clone --depth=1 --branch n6.0 https://git.ffmpeg.org/ffmpeg.git ffmpeg

    - name: Build FFmpeg for ARMv7
      run: |
        export API=21
        export NDK=$ANDROID_NDK_HOME
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export AR=$TOOLCHAIN/bin/llvm-ar
        export AS=$TOOLCHAIN/bin/llvm-as
        export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang
        export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang++
        export LD=$TOOLCHAIN/bin/ld
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        export NM=$TOOLCHAIN/bin/llvm-nm
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib

        cd ffmpeg
        ./configure \
          --prefix=$PWD/build/armeabi-v7a \
          --target-os=android \
          --arch=armv7a \
          --cpu=armv7-a \
          --enable-shared \
          --enable-gpl \
          --disable-libdrm \
          --enable-omx \
          --enable-omx-rpi \
          --enable-v4l2-m2m \
          --disable-vulkan \
          --disable-static \
          --disable-doc \
          --disable-programs \
          --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
          --cc=$CC \
          --cxx=$CXX \
          --ar=$AR \
          --nm=$NM \
          --strip=$STRIP \
          --ranlib=$RANLIB \
          --sysroot=$TOOLCHAIN/sysroot \
          --extra-cflags="-O3 -fPIC" \
          --extra-ldflags="-lm"
        make -j2
        make install

    - name: Build Android APK
      run: |
        mkdir -p app/src/main/jniLibs/armeabi-v7a
        cp ffmpeg/build/armeabi-v7a/lib/*.so app/src/main/jniLibs/armeabi-v7a/

        ./gradlew assembleRelease

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: "FFmpeg GUI Android Build ${{ github.run_number }}"
        files: app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
