name: Build FFmpeg Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git wget unzip build-essential pkg-config yasm cmake autoconf automake libtool

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 21
        ndk: 25.2.9519653
        cmake: 3.22.1
        build-tools: 30.0.3

    - name: Download FFmpeg source
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-6.0.tar.bz2
        tar xjf ffmpeg-6.0.tar.bz2
        mv ffmpeg-6.0 ffmpeg

    - name: Configure NDK toolchain
      run: |
        export API=21
        export NDK=$ANDROID_NDK_HOME
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export AR=$TOOLCHAIN/bin/llvm-ar
        export AS=$TOOLCHAIN/bin/llvm-as
        export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang
        export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang++
        export LD=$TOOLCHAIN/bin/ld
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        export NM=$TOOLCHAIN/bin/llvm-nm
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib

        cd ffmpeg
        ./configure \
          --prefix=$PWD/build/armeabi-v7a \
          --target-os=android \
          --arch=armv7a \
          --cpu=armv7-a \
          --enable-shared \
          --enable-gpl \
          --enable-libdrm \
          --enable-omx \
          --enable-omx-rpi \
          --enable-v4l2-m2m \
          --disable-vulkan \
          --disable-static \
          --disable-doc \
          --disable-programs \
          --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
          --cc=$CC \
          --cxx=$CXX \
          --ar=$AR \
          --nm=$NM \
          --strip=$STRIP \
          --ranlib=$RANLIB \
          --sysroot=$TOOLCHAIN/sysroot \
          --extra-cflags="-O3 -fPIC" \
          --extra-ldflags="-lm"

    - name: Build FFmpeg
      run: |
        cd ffmpeg
        make -j2
        make install

    - name: Prepare Android project
      run: |
        mkdir -p app/src/main/jniLibs/armeabi-v7a
        cp -v ffmpeg/build/armeabi-v7a/lib/*.so app/src/main/jniLibs/armeabi-v7a/

    - name: Build APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: "FFmpeg Android Build ${{ github.run_number }}"
        files: app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
