name: Build FFmpeg Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: sdkmanager --install "ndk;25.2.9519653"

    - name: Create project structure
      run: |
        mkdir -p app/src/main/java/com/example/ffmpegui
        mkdir -p app/src/main/res/layout
        mkdir -p app/src/main/res/values

        # settings.gradle
        cat <<'EOF' > settings.gradle
        rootProject.name = "FFmpegUI"
        include ':app'
        EOF

        # gradle.properties
        cat <<'EOF' > gradle.properties
        org.gradle.jvmargs=-Xmx2g
        android.useAndroidX=true
        android.enableJetifier=true
        EOF

        # build.gradle (root)
        cat <<'EOF' > build.gradle
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:8.1.0'
            }
        }
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF

        # app/build.gradle
        cat <<'EOF' > app/build.gradle
        plugins {
            id 'com.android.application'
        }
        android {
            namespace "com.example.ffmpegui"
            compileSdk 33
            defaultConfig {
                applicationId "com.example.ffmpegui"
                minSdk 21
                targetSdk 33
                versionCode 1
                versionName "1.0"
                ndk {
                    abiFilters "armeabi-v7a"
                }
            }
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
        }
        dependencies {
            implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
        }
        EOF

        # MainActivity.java
        cat <<'EOF' > app/src/main/java/com/example/ffmpegui/MainActivity.java
        package com.example.ffmpegui;
        import android.app.Activity;
        import android.os.Bundle;
        import android.widget.*;
        public class MainActivity extends Activity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_main);
            }
        }
        EOF

        # layout XML
        cat <<'EOF' > app/src/main/res/layout/activity_main.xml
        <?xml version="1.0" encoding="utf-8"?>
        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:orientation="vertical" android:layout_width="match_parent"
            android:layout_height="match_parent" android:padding="16dp">
            <Spinner android:id="@+id/videoCodecSpinner"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>
            <Spinner android:id="@+id/audioCodecSpinner"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>
            <EditText android:id="@+id/extraParams"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="Extra FFmpeg parameters"/>
            <Button android:id="@+id/startBtn"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Start Encoding"/>
        </LinearLayout>
        EOF

        # strings.xml
        cat <<'EOF' > app/src/main/res/values/strings.xml
        <resources>
            <string name="app_name">FFmpegUI</string>
        </resources>
        EOF

    - name: Download and build FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y yasm pkg-config curl

        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        ./configure \
          --prefix=$PWD/build \
          --enable-cross-compile \
          --target-os=android \
          --arch=arm \
          --cpu=armv7-a \
          --cross-prefix=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21- \
          --enable-gpl \
          --enable-nonfree \
          --enable-encoder=h264_v4l2m2m,mpeg4_v4l2m2m,vp8_v4l2m2m,h264_omx \
          --enable-decoder=h264,mpeg4,vp8 \
          --enable-shared \
          --disable-static
        make -j$(nproc)
        make install
        cd ..

        mkdir -p app/libs
        cp ffmpeg/build/lib/*.so app/libs/

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FFmpegUI.apk
        path: app/build/outputs/apk/release/app-release.apk
