name: Android ARMv7 FFmpeg mediacodec build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make automake autoconf libtool pkg-config unzip

      - name: Download Android NDK
        run: |
          mkdir -p $HOME/android-ndk
          cd $HOME/android-ndk
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip -q android-ndk-r25c-linux.zip
          mv android-ndk-r25c ndk
          echo "ANDROID_NDK_HOME=$HOME/android-ndk/ndk" >> $GITHUB_ENV

      - name: Download FFmpeg
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          git checkout n6.0

      - name: Build FFmpeg ARMv7 with MediaCodec
        run: |
          export API=21
          export NDK=$ANDROID_NDK_HOME
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export AR=$TOOLCHAIN/bin/llvm-ar
          export AS=$TOOLCHAIN/bin/llvm-as
          export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang
          export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang++
          export LD=$TOOLCHAIN/bin/ld
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          export NM=$TOOLCHAIN/bin/llvm-nm
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          
          cd ffmpeg
          ./configure \
            --prefix=$PWD/build/armeabi-v7a \
            --target-os=android \
            --arch=armv7a \
            --cpu=armv7-a \
            --enable-shared \
            --enable-gpl \
            --enable-jni \
            --enable-mediacodec \
            --enable-decoder=h264_mediacodec \
            --enable-encoder=h264_mediacodec \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
            --cc=$CC \
            --cxx=$CXX \
            --ar=$AR \
            --nm=$NM \
            --strip=$STRIP \
            --ranlib=$RANLIB \
            --sysroot=$TOOLCHAIN/sysroot \
            --extra-cflags="-O3 -fPIC" \
            --extra-ldflags="-lm"
          make -j$(nproc)
          make install

      - name: Package build
        run: |
          mkdir -p output
          cd ffmpeg/build
          zip -r ../../output/ffmpeg-armv7-mediacodec.zip .
          cd ../..

      - name: Create Git Tag
        run: |
          TAG="build-$(date +'%Y%m%d-%H%M%S')"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: output/ffmpeg-armv7-mediacodec.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
