name: Build FFmpeg ARMv7 + MediaCodec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip pkg-config

      - name: Download Android NDK
        run: |
          mkdir -p $HOME/android-ndk
          cd $HOME/android-ndk
          curl -LO https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          mv android-ndk-r26d ndk
        env:
          ANDROID_NDK_HOME: $HOME/android-ndk/ndk

      - name: Build FFmpeg
        run: |
          set -e
          export API=21
          export NDK=$ANDROID_NDK_HOME
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export AR=$TOOLCHAIN/bin/llvm-ar
          export AS=$TOOLCHAIN/bin/llvm-as
          export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang
          export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang++
          export LD=$TOOLCHAIN/bin/ld
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          export NM=$TOOLCHAIN/bin/llvm-nm
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export SYSROOT=$TOOLCHAIN/sysroot

          cd ffmpeg
          make distclean || true
          git clean -fdx || true

          ./configure \
            --prefix=$PWD/build/armeabi-v7a \
            --target-os=android \
            --arch=armv7a \
            --cpu=armv7-a \
            --enable-cross-compile \
            --enable-shared \
            --enable-gpl \
            --enable-jni \
            --enable-mediacodec \
            --enable-decoder=h264_mediacodec \
            --enable-decoder=hevc_mediacodec \
            --enable-decoder=mpeg4_mediacodec \
            --enable-encoder=h264_mediacodec \
            --disable-libdrm \
            --disable-vulkan \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
            --cc=$CC \
            --cxx=$CXX \
            --ar=$AR \
            --nm=$NM \
            --strip=$STRIP \
            --ranlib=$RANLIB \
            --sysroot=$SYSROOT \
            --extra-cflags="-O3 -fPIC" \
            --extra-ldflags="-lm"

          make -j2
          make install

      - name: Create output zip
        run: |
          mkdir -p output
          cd ffmpeg/build/armeabi-v7a
          zip -r ../../../../output/ffmpeg-armv7-mediacodec.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-armv7-mediacodec
          path: output/ffmpeg-armv7-mediacodec.zip
